/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.modul1;
import javax.swing.JOptionPane;

/**
 *
 * @author user
 */
public class Input extends javax.swing.JFrame {

    /**
     * Creates new form Mod1
     */
    public Input() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jInternalFrame1 = new javax.swing.JInternalFrame();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        TFnama = new javax.swing.JTextField();
        TFtempat = new javax.swing.JTextField();
        TFtanggal = new javax.swing.JTextField();
        TFalamat = new javax.swing.JTextField();
        TFtelp = new javax.swing.JTextField();
        TFemail = new javax.swing.JTextField();
        TFprodi = new javax.swing.JTextField();
        BTreset = new javax.swing.JButton();
        CBfakultas = new javax.swing.JComboBox<>();
        RBlaki = new javax.swing.JRadioButton();
        RBperempuan = new javax.swing.JRadioButton();
        BTbatal = new javax.swing.JButton();
        CheckBox1 = new javax.swing.JCheckBox();
        BTsimpan = new javax.swing.JButton();

        jButton1.setText("jButton1");

        jInternalFrame1.setVisible(true);

        javax.swing.GroupLayout jInternalFrame1Layout = new javax.swing.GroupLayout(jInternalFrame1.getContentPane());
        jInternalFrame1.getContentPane().setLayout(jInternalFrame1Layout);
        jInternalFrame1Layout.setHorizontalGroup(
            jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jInternalFrame1Layout.setVerticalGroup(
            jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 0, 153));

        jPanel2.setBackground(new java.awt.Color(0, 204, 204));

        jLabel1.setFont(new java.awt.Font("Yeseva One", 1, 18)); // NOI18N
        jLabel1.setText("UNIVERSITAS TRUNOJOYO MADURA");

        jLabel2.setText("Jl. Raya Telang, PO Box. 2 kamal, Bangkalan- Madura");

        jLabel3.setText("Telp : (031) 3011146,Fax. (031)3011506");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(98, 98, 98)
                        .addComponent(jLabel2))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(78, 78, 78)
                        .addComponent(jLabel1))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(130, 130, 130)
                        .addComponent(jLabel3)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addContainerGap(17, Short.MAX_VALUE))
        );

        jLabel4.setForeground(new java.awt.Color(228, 228, 228));
        jLabel4.setText("Nama               :");

        jLabel5.setForeground(new java.awt.Color(228, 228, 228));
        jLabel5.setText("Tempat Lahir    :");

        jLabel6.setForeground(new java.awt.Color(228, 228, 228));
        jLabel6.setText("Tanggal Lahir   :");

        jLabel7.setForeground(new java.awt.Color(228, 228, 228));
        jLabel7.setText("Jenis Kelamin   :");

        jLabel8.setForeground(new java.awt.Color(228, 228, 228));
        jLabel8.setText("No. Telp           :");

        jLabel9.setForeground(new java.awt.Color(228, 228, 228));
        jLabel9.setText("Alamat             :");

        jLabel10.setForeground(new java.awt.Color(228, 228, 228));
        jLabel10.setText("Prodi                :");

        jLabel11.setForeground(new java.awt.Color(228, 228, 228));
        jLabel11.setText("Email                :");

        jLabel12.setForeground(new java.awt.Color(228, 228, 228));
        jLabel12.setText("Fakultas           :");

        TFtempat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TFtempatActionPerformed(evt);
            }
        });

        TFtanggal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TFtanggalActionPerformed(evt);
            }
        });

        BTreset.setText("Reset");
        BTreset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTresetActionPerformed(evt);
            }
        });

        CBfakultas.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Fakultas Teknik", "Fakultas pendidikan", "Fakultas pertanian", "Fakultas Hukum", "Fakultas Fisib", "Fakultas Keislaman", "Fakultas Ekonomi" }));

        buttonGroup1.add(RBlaki);
        RBlaki.setForeground(new java.awt.Color(226, 225, 225));
        RBlaki.setText("Laki-laki");
        RBlaki.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RBlakiActionPerformed(evt);
            }
        });

        buttonGroup1.add(RBperempuan);
        RBperempuan.setForeground(new java.awt.Color(222, 221, 221));
        RBperempuan.setText("Perempuan");

        BTbatal.setText("Batal");
        BTbatal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTbatalActionPerformed(evt);
            }
        });

        CheckBox1.setForeground(new java.awt.Color(219, 217, 217));
        CheckBox1.setText("Data Yang Saya Masukkan Sudah Benar");
        CheckBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CheckBox1ActionPerformed(evt);
            }
        });

        BTsimpan.setText("Simpan");
        BTsimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTsimpanActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(56, 56, 56)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel11)
                                    .addComponent(jLabel10)
                                    .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel12, javax.swing.GroupLayout.Alignment.TRAILING))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(TFemail)
                                    .addComponent(TFprodi)
                                    .addComponent(CBfakultas, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(TFtelp))
                                .addGap(69, 69, 69))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(2, 2, 2)
                                .addComponent(CheckBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jLabel5)
                                        .addComponent(jLabel4))
                                    .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(TFnama, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(TFtempat, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(TFtanggal, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(RBlaki)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(RBperempuan))
                                    .addComponent(TFalamat, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(103, 103, 103)
                                .addComponent(BTbatal)
                                .addGap(18, 18, 18)
                                .addComponent(BTreset)
                                .addGap(18, 18, 18)
                                .addComponent(BTsimpan)))
                        .addGap(68, 70, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(TFnama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TFtempat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TFtanggal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(RBlaki)
                    .addComponent(RBperempuan))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TFalamat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TFtelp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TFemail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TFprodi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel12)
                    .addComponent(CBfakultas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(CheckBox1)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BTreset)
                    .addComponent(BTbatal)
                    .addComponent(BTsimpan))
                .addGap(41, 41, 41))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BTresetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTresetActionPerformed
        // TODO add your handling code here:
        TFnama.setText("");
        TFtanggal.setText("");
        TFtempat.setText("");
        TFalamat.setText("");
        TFtelp.setText("");
        TFemail.setText("");
        TFprodi.setText("");
        CBfakultas.setSelectedIndex(0); 
        buttonGroup1.clearSelection();
        
    }//GEN-LAST:event_BTresetActionPerformed

    private void TFtanggalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TFtanggalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TFtanggalActionPerformed

    private void TFtempatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TFtempatActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TFtempatActionPerformed

    private void RBlakiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RBlakiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_RBlakiActionPerformed

    private void BTbatalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTbatalActionPerformed
        // TODO add your handling code here:
        if (JOptionPane.showConfirmDialog(null, "Yakin keluar?", "Konfirmasi Keluar", JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION) {
        System.exit(0);
        }
    }//GEN-LAST:event_BTbatalActionPerformed

    private void CheckBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CheckBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CheckBox1ActionPerformed

    private void BTsimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTsimpanActionPerformed
        // TODO add your handling code here:
        if (!CheckBox1.isSelected()) {
        //kondisi untuk checkbox jika tidak dicentang
        JOptionPane.showMessageDialog(null, "Anda harus mencentang sebelum menyimpan!", "Peringatan", JOptionPane.WARNING_MESSAGE);
        } 
        else {
           String nama = TFnama.getText();
           String ttl = TFtanggal.getText();
           String asal = TFtempat.getText();
           String jeniskelamin =RBlaki.isSelected()? "Pria" : "Wanita";
           String telepon = TFtelp.getText();
           String alamat = TFalamat.getText();
           String email = TFemail.getText();
           String prodi = TFprodi.getText();
           String fakultas = CBfakultas.getSelectedItem().toString();
           
           Output tampilan = new Output();
           tampilan.TFnama2.setText(TFnama.getText());
           tampilan.TFtanggal2.setText(TFnama.getText());
           tampilan.TFtempat2.setText(TFtempat.getText());
           tampilan.TFtelp2.setText(TFtelp.getText());
           tampilan.TFalamat2.setText(TFalamat.getText());
           tampilan.TFemail2.setText(TFemail.getText());
           tampilan.TFprodi2.setText(TFprodi.getText());
           
           
           
           if (RBlaki.isSelected()==true) {
            tampilan.TFkelamin2.setText(RBlaki.getText());
            } else if (RBperempuan.isSelected()==true) {
            tampilan.TFkelamin2.setText(RBperempuan.getText());
            }
           int selectedIndex = CBfakultas.getSelectedIndex();
            if (selectedIndex == 0){
               tampilan.TFfakultas2.setText("");
            }else {
                String value;
                value = CBfakultas.getSelectedItem().toString();
                tampilan.TFfakultas2.setText(value);
            }            
            
           tampilan.setVisible(true);
           
            if(CheckBox1.isSelected()){
                if(TFnama.getText().trim().isEmpty() || TFtempat.getText().trim().isEmpty() 
                || TFtanggal.getText().trim().isEmpty() || TFemail.getText().trim().isEmpty()
                ||TFtelp.getText().trim().isEmpty() ||TFprodi.getText().trim().isEmpty() ||RBlaki.equals(false) 
                || CBfakultas.getSelectedItem().toString(). isEmpty()
                ){        
                    int alert = JOptionPane.showConfirmDialog(
                    this,
                    "Silahkan Lengkapi Data",
                    "Data Belum lengkap",
                    JOptionPane.OK_CANCEL_OPTION,
                    JOptionPane.WARNING_MESSAGE
                );
                }else{
                tampilan.setVisible(true);
                this.dispose();
            }
            }else{
                int alert = JOptionPane.showConfirmDialog(
                this,
                "Silahkan Konfirmasi Data",
                "Data Belum lengkap",
                JOptionPane.OK_CANCEL_OPTION,
                JOptionPane.WARNING_MESSAGE);
            }
           this.dispose();
           
        }        
    }//GEN-LAST:event_BTsimpanActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Input.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Input.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Input.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Input.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Input().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BTbatal;
    private javax.swing.JButton BTreset;
    private javax.swing.JButton BTsimpan;
    private javax.swing.JComboBox<String> CBfakultas;
    private javax.swing.JCheckBox CheckBox1;
    private javax.swing.JRadioButton RBlaki;
    private javax.swing.JRadioButton RBperempuan;
    private javax.swing.JTextField TFalamat;
    private javax.swing.JTextField TFemail;
    public javax.swing.JTextField TFnama;
    private javax.swing.JTextField TFprodi;
    public javax.swing.JTextField TFtanggal;
    private javax.swing.JTextField TFtelp;
    public javax.swing.JTextField TFtempat;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JButton jButton1;
    private javax.swing.JInternalFrame jInternalFrame1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
